### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ProdByPengu** [open-quantum-safe/liboqs-cpp#20] opened 2024-07-03 08:26 UTC
@alineha How are you building your project? Please follow the instructions in https://github.com/open-quantum-safe/liboqs-cpp/blob/main/README.md. Seems like a compiler misconfiguration.

_Originally posted by @vsoftco in https://github.com/open-quantum-safe/liboqs-cpp/issues/14#issuecomment-1919328193_
            
Getting the same "Error: 'LIBOQS_CPP_VERSION_NUM': undeclared identifier" error. Followed all of the install instructions correctly.

**Comment by vsoftco** [comment] 2024-08-06 19:28
@ProdByPengu Can you please specify which compiler you're using and the commands that you run? I am not able to reproduce it.

**Comment by ProdByPengu** [comment] 2024-08-06 20:36
> @ProdByPengu Can you please specify which compiler you're using and the commands that you run? I am not able to reproduce it.

Visual studio and I'm on windows

**Comment by vsoftco** [comment] 2024-08-27 16:59
@ProdByPengu can you please describe here how you compile and build the wrapper? I cannot reproduce. Which steps from https://github.com/open-quantum-safe/liboqs-cpp?tab=readme-ov-file#installation fail?

**Comment by vsoftco** [comment] 2024-09-03 11:38
Closing as we can not reproduce

**Closed as completed by vsoftco** 2024-09-03 11:38 UTC
